name: 'ng2_dart_router_demo'
version: 0.0.1
description: A simple example of angular 2 router
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: "2.0.0-alpha.46"
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
  - dart_to_js_script_rewriter
  - angular2:
      entry_points: web/main.dart
